### ISSUE TITLE
"Import Lightmap Info" feature in blender not accounting for German formatting.

### ISSUE THREAD

**Issue by Aitolda** [vircadia/unity-to-vircadia-pipeline#3]
My understanding is that a number such "1.000877" as exported using German formatting would be "1,000877" using a comma in the decimal place. I believe we can simply adjust the blender plugins "Import Lightmap Info" feature to account for this.

**Comment by digisomni** [comment]
Can we be sure this is dynamically handled in case the numbers come in normal as well (not using commas)?

**Comment by Aitolda** [comment]
> Can we be sure this is dynamically handled in case the numbers come in normal as well (not using commas)?

That is my intention. Yes.

**Comment by Aitolda** [comment]
This has been addressed in [PR4](https://github.com/vircadia/unity-to-vircadia-pipeline/pull/4)
